config/routes.rb
Rails.application.routes.draw do
  root 'ests#index'
  
  resources :ests
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/est.rb
class Est < ApplicationRecord
    validates :nombres, :apellidos, :carrera, presence:true
    validates :carnet, numericality:true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/ests_controller.rb
class EstsController < ApplicationController
  before_action :set_est, only: %i[ show edit update destroy ]

  # GET /ests or /ests.json
  def index
    @ests = Est.all
  end

  # GET /ests/1 or /ests/1.json
  def show
  end

  # GET /ests/new
  def new
    @est = Est.new
  end

  # GET /ests/1/edit
  def edit
  end

  # POST /ests or /ests.json
  def create
    @est = Est.new(est_params)

    respond_to do |format|
      if @est.save
        format.html { redirect_to @est, notice: "Est was successfully created." }
        format.json { render :show, status: :created, location: @est }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @est.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ests/1 or /ests/1.json
  def update
    respond_to do |format|
      if @est.update(est_params)
        format.html { redirect_to @est, notice: "Est was successfully updated." }
        format.json { render :show, status: :ok, location: @est }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @est.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ests/1 or /ests/1.json
  def destroy
    @est.destroy!

    respond_to do |format|
      format.html { redirect_to ests_path, status: :see_other, notice: "Est was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_est
      @est = Est.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def est_params
      params.require(:est).permit(:nombres, :apellidos, :carrera, :carnet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ests_helper.rb
module EstsHelper
end

app/views/ests/_est.html.erb
<div id="<%= dom_id est %>">
  <p>
    <strong>Nombres:</strong>
    <%= est.nombres %>
  </p>

  <p>
    <strong>Apellidos:</strong>
    <%= est.apellidos %>
  </p>

  <p>
    <strong>Carrera:</strong>
    <%= est.carrera %>
  </p>

  <p>
    <strong>Carnet:</strong>
    <%= est.carnet %>
  </p>

</div>

app/views/ests/_form.html.erb
<%= form_with(model: est) do |form| %>
  <% if est.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(est.errors.count, "error") %> prohibited this est from being saved:</h2>

      <ul>
        <% est.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombres, style: "display: block" %>
    <%= form.text_field :nombres %>
  </div>

  <div>
    <%= form.label :apellidos, style: "display: block" %>
    <%= form.text_field :apellidos %>
  </div>

  <div>
    <%= form.label :carrera, style: "display: block" %>
    <%= form.text_field :carrera %>
  </div>

  <div>
    <%= form.label :carnet, style: "display: block" %>
    <%= form.text_field :carnet %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ests/edit.html.erb
<% content_for :title, "Editing est" %>

<h1>Editing est</h1>

<%= render "form", est: @est %>

<br>

<div>
  <%= link_to "Show this est", @est %> |
  <%= link_to "Back to ests", ests_path %>
</div>

app/views/ests/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Ests" %>

<h1>Ests</h1>

<div id="ests">
  <% @ests.each do |est| %>
    <%= render est %>
    <p>
      <%= link_to "Show this est", est %>
    </p>
  <% end %>
</div>

<%= link_to "New est", new_est_path %>

app/views/ests/new.html.erb
<% content_for :title, "New est" %>

<h1>New est</h1>

<%= render "form", est: @est %>

<br>

<div>
  <%= link_to "Back to ests", ests_path %>
</div>

app/views/ests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @est %>

<div>
  <%= link_to "Edit this est", edit_est_path(@est) %> |
  <%= link_to "Back to ests", ests_path %>

  <%= button_to "Destroy this est", @est, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Estudiante" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>